"""add is_custom column

Revision ID: 67f89b664e58
Revises: 8bbb054b3c92
Create Date: 2025-12-31 18:46:04.420648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f89b664e58'
down_revision: Union[str, Sequence[str], None] = '8bbb054b3c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('is_custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'is_custom')
    # ### end Alembic commands ###
